### ISSUE TITLE
statsd_gauge and statsd_timing do not support sample_rate

### ISSUE THREAD

**Issue by louismunro** [romanbsd/statsd-c-client#12]
I am not sure if this is deliberate, and what was the reasoning behind it.

I could try to contribute a PR if that is acceptable.

**Comment by romanbsd** [comment]
I don't think that these are defined in the spec:
https://github.com/b/statsd_spec

**Comment by louismunro** [comment]
Good point.
I was basing my understanding on the Etsy implementation, Especially Etsy/StatsD.pm.
